Add PSTAKE
ThrusterX/thruster-token-list pull request #24
Opened 2024-06-04 11:43 UTC by ChipKlutzy

### Checklist
- [x] Token Address in lowercase
- [x] Link to verified contract on Blastscan
- [x] Description of token if non-standard ERC20, e.g. has tax, OFT token, bridged XERC20, ERC-404, etc.
- [x] An SVG <150 KB in size, cropped to be a circle. **Rectangles and other shapes of images will not be accepted.**
- [x] Token category you would like to be listed under
    - Current categories: DeFi, Memecoin, Stablecoin, Other

### Additional Information
-

2024-06-06 04:56 UTC, 0xjazper commented on chains/81457/token-list.json
> +    "tokenAddress": "0xd9a1266a23ed88fc9cb12454a5d6d338b65a3302",
u did not run the script to autogenerate this file, it should be alphabetically ordered

2024-06-06 04:56 UTC, 0xjazper requested changes
as per comment

2024-06-06 13:30 UTC, ChipKlutzy commented on chains/81457/token-list.json
> +    "tokenAddress": "0xd9a1266a23ed88fc9cb12454a5d6d338b65a3302",
Yeah the problem is when ever I run the script (./update_list.sh), it gives me blank output in "token-list.json" file.
Refer this [commit](https://github.com/ThrusterX/thruster-token-list/pull/24/commits/88ec868c324819c243f0f27b686c58b554983f66).

2024-06-06 15:08 UTC, 0xjazper commented on chains/81457/token-list.json
> +    "tokenAddress": "0xd9a1266a23ed88fc9cb12454a5d6d338b65a3302",
are you running the script from the root directory?

2024-06-07 05:29 UTC, 0xjazper commented
i went ahead and added a pr for you here: https://github.com/ThrusterX/thruster-token-list/pull/30

will leave this pr up for a day or two before closing if you have any additional questions or concerns, otherwise, the token should be added for you

2024-06-08 02:48 UTC, closed without merging